# ==============================
# Local H2 Database
# ==============================

spring.datasource.url=jdbc:h2:file:./data/replan-local;MODE=MySQL;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Entity를 기준으로 테이블 자동 생성 및 수정
spring.jpa.hibernate.ddl-auto=update

# 실행되는 SQL 확인
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 세션 종료 후 지연 로딩 방지
spring.jpa.open-in-view=false

# H2 웹 콘솔
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 날짜 및 시간
spring.jackson.time-zone=Asia/Seoul